# Generated by Django 5.2.7 on 2025-10-29 23:33

import deteccion.util
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: administrador, supervisor, obrero ', max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del rol que cumple este cargo (opcional).', null=True, verbose_name='Descripción del Cargo')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva este cargo si ya no se usa en el sistema.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(default='bi bi-calendar-x-fill', max_length=100, verbose_name='Icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula o RUC')),
                ('image', models.ImageField(blank=True, max_length=1024, null=True, upload_to='deteccion/users/', verbose_name='Imagen de perfil')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('direction', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': (('change_userprofile', 'Cambiar perfil de Usuario'), ('change_userpassword', 'Cambiar contraseña de Usuario')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre del Empleado')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido del Empleado')),
                ('cedula_ecuatoriana', models.CharField(help_text='Ingrese el número de cédula sin espacios ni guiones.', max_length=10, validators=[deteccion.util.valida_cedula], verbose_name='Cédula')),
                ('dni', models.CharField(blank=True, help_text='Pasaporte, DNI, CURP u otro documento válido internacionalmente.', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un documento válido (letras, números, guiones o puntos).', regex='^[A-Za-z0-9\\-\\. ]{5,30}$')], verbose_name='Dni internacional')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='deteccion.cargo', verbose_name='Cargo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='Url')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='bi bi-x-octagon', max_length=100, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Es activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='deteccion.menu', verbose_name='Menu')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['menu', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_permissions', to='auth.group', verbose_name='Grupo')),
                ('permissions', models.ManyToManyField(to='auth.permission', verbose_name='Permisos')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_permissions', to='deteccion.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Grupo módulo permiso',
                'verbose_name_plural': 'Grupos módulos permisos',
                'ordering': ['group', 'module'],
                'constraints': [models.UniqueConstraint(fields=('group', 'module'), name='unique_group_module')],
            },
        ),
    ]
