# Generated by Django 5.2.7 on 2025-11-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('missing', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('positive', 'Positiva')], default='high', max_length=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
